#!/usr/bin/env zsh

# A simple script for setting up OSX dev environment.

CODEDIR=$HOME/Development
pushd .
mkdir -p $CODEDIR
cd $CODEDIR

function install() {
  echo "Installing $1..."
  brew install $1
}

echo "Enter new hostname of the machine"
	read hostname
	echo "Setting new hostname..."
	scutil –set HostName "$hostname"

echo "Checking for SSH key, generating one if it doesn't exist..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Homebrew..."
  ruby -e "$(curl -fsSL https://gist.github.com/raw/323731/install_homebrew.rb)"
  brew update

echo "Installing Homebrew packages..."
  install Redis Python Python3 WGet Node HTop GHC Haskell-platform Scala GnuPG Growlnotify Hub
  source ~/.zshrc

echo "Installing NPM..."
  curl http://npmjs.org/install.sh | sh

echo "Installing python things..."
  source install_python

echo "Symlinking config files..."
  source symlink_dotfiles

popd

echo "OS X tweaking..."
  # echo "Disabling useless Safari page previews..."
  # defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2
  # echo "Disabling warning dialogue on downloaded applications..."
  # defaults write com.apple.LaunchServices LSQuarantine -bool NO
	echo "Changing default screenshot location to ~/Downloads/..."
	defaults write com.apple.screencapture location ~/Downloads/
	killall SystemUIServer
