#!/bin/sh

# Some code taken from github.com/penpen/dotfiles.

dev="$HOME/Development"
dotfiles="$dev/paulmillr/dotfiles"
bin="/usr/local/bin"

link() {
  echo "Linking '$1' to '$2'"
  rm $2
  ln -s $1 $2
}

link_home() {
  link "$dotfiles/$1" "$HOME/$2"
}

link_bin() {
	link "$dotfiles/$1" "$bin/$1"
}

link_home zshrc.sh .zshrc
link_home gitconfig .gitconfig
link_home gitignore .gitignore

if [[ `uname` == 'Darwin' ]]; then
  link_home tm_properties .tm_properties
  link_home Textmate/ "Library/Application Support/Textmate"
fi
