#!/bin/sh

# Some code taken from github.com/penpen/dotfiles.

DOTFILES="$HOME/Development/dotfiles"
BIN="/usr/local/bin"

link() {
  old=$1
  new=$2

  rm "$new"
  ln -s "$old" "$new"
}

link_home() {
  link "$DOTFILES/$1" "$HOME/$2"
}

link_bin() {
	link "$DOTFILES/$1" "$BIN/$1"
}

link_home zshrc.sh .zshrc
link_home gitconfig .gitconfig
link_home gitignore .gitignore
link_home tm_properties .tm_properties
link_home Textmate/ "Library/Application Support/Textmate"
